title: Engine
email: your-email@example.com
description: "A collection of Linux features, commands, tools and hacks"

domain: asiangoldfish.github.io
url: https://asiangoldfish.github.io
baseurl: "/Engine"
github_username: asiangoldfish

remote_theme: just-the-docs/just-the-docs

# All files that shouldn't be accessible by the web client
exclude:
  - "node_modules/"
  - "*.gemspec"
  - "*.gem"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "script/"
  - "LICENSE.txt"
  - "lib/"
  - "bin/"
  - "README.md"
  - "docs/test"
  - "vendor/bundle"

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

color_scheme: dark

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Define collections
collections:
  docs:
    permalink: ":path:output_ext"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false

aux_links:
  "Source Code":
    - "//github.com/asiangoldfish/Engine"
  
aux_links_new_tab: true
